import type { Template } from './types';

export const noteTemplate: Template = {
  id: 'note',
  name: '便签笔记',
  category: 'note',
  thumbnail: '',
  layout: {
    aspectRatio: '1:1',
    width: 400,
    height: 400,
    textAreas: [
      {
        id: 'tag',
        type: 'subtitle',
        position: { x: 34, y: 38 },
        width: 'calc(100% - 150px)',
        defaultText: 'DESK NOTE',
        style: {
          fontFamily: 'IBM Plex Sans',
          fontSize: 11,
          fontWeight: 700,
          lineHeight: 1.2,
          textAlign: 'left',
          color: '#8a5a3b',
        },
      },
      {
        id: 'title',
        type: 'title',
        position: { x: 34, y: 78 },
        width: 'calc(100% - 68px)',
        defaultText: '周三重点',
        style: {
          fontFamily: 'Noto Serif SC',
          fontSize: 28,
          fontWeight: 700,
          lineHeight: 1.3,
          textAlign: 'left',
        },
      },
      {
        id: 'content',
        type: 'body',
        position: { x: 34, y: 158 },
        width: 'calc(100% - 68px)',
        defaultText: '01. 完成首页文案终稿\n02. 回复客户修改意见\n03. 整理本周复盘要点',
        style: {
          fontFamily: 'IBM Plex Sans',
          fontSize: 16,
          fontWeight: 500,
          lineHeight: 1.75,
          textAlign: 'left',
        },
      },
      {
        id: 'footer',
        type: 'body',
        position: { x: 34, y: 320 },
        width: 'calc(100% - 92px)',
        defaultText: '17:30 前完成最终校对，并同步给团队。',
        style: {
          fontFamily: 'IBM Plex Sans',
          fontSize: 12,
          fontWeight: 600,
          lineHeight: 1.5,
          color: '#6c5848',
          textAlign: 'left',
        },
      },
    ],
  },
  defaultContent: {
    tag: 'DESK NOTE',
    title: '周三重点',
    content: '01. 完成首页文案终稿\n02. 回复客户修改意见\n03. 整理本周复盘要点',
    footer: '17:30 前完成最终校对，并同步给团队。',
  },
  style: {
    fontFamily: 'IBM Plex Sans',
    fontSize: 16,
    fontSizeScale: 1,
    lineHeight: 1.7,
    lineHeightOffset: 0,
    padding: 34,
    backgroundColor: '#efe3d2',
    textColor: '#2f241d',
  },
  elementDefaults: {
    icon: true,
    icon2: true,
    date: true,
    author: false,
    count: true,
    qrcode: false,
    page: false,
    watermark: true,
  },
};
