import type { Template } from './types';

export const posterTemplate: Template = {
  id: 'poster',
  name: '小红书大字报',
  category: 'poster',
  thumbnail: '',
  layout: {
    aspectRatio: '3:4',
    width: 375,
    height: 500,
    textAreas: [
      {
        id: 'date',
        type: 'subtitle',
        position: { x: 92, y: 34 },
        width: 'calc(100% - 168px)',
        defaultText: '2026 / 03 / 11',
        style: {
          fontFamily: 'system-ui',
          fontSize: 11,
          fontWeight: 700,
          lineHeight: 1.4,
          textAlign: 'left',
          color: '#64748b',
        },
      },
      {
        id: 'title',
        type: 'title',
        position: { x: 28, y: 126 },
        width: 'calc(100% - 56px)',
        defaultText: '普通人做内容\n先学会这3件事',
        style: {
          fontFamily: 'system-ui',
          fontSize: 52,
          fontWeight: 800,
          lineHeight: 1.04,
          textAlign: 'left',
        },
      },
      {
        id: 'posterBody',
        type: 'body',
        position: { x: 30, y: 302 },
        width: 'calc(100% - 108px)',
        defaultText: '补一句说明，把观点说完整。',
        style: {
          fontFamily: 'system-ui',
          fontSize: 15,
          fontWeight: 600,
          lineHeight: 1.6,
          textAlign: 'left',
          color: '#334155',
        },
      },
      {
        id: 'author',
        type: 'subtitle',
        position: { x: 28, y: 454 },
        width: 'calc(100% - 160px)',
        defaultText: 'JIANDAN CARD',
        style: {
          fontFamily: 'system-ui',
          fontSize: 13,
          fontWeight: 700,
          lineHeight: 1.4,
          textAlign: 'left',
          color: '#475569',
        },
      },
    ],
  },
  defaultContent: {
    date: '2026 / 03 / 11',
    title: '普通人做内容\n先学会这3件事',
    posterBody: '补一句说明，把观点说完整。',
    author: 'JIANDAN CARD',
  },
  style: {
    fontFamily: 'system-ui',
    fontSize: 24,
    fontSizeScale: 1,
    lineHeight: 1.2,
    lineHeightOffset: 0,
    padding: 28,
    backgroundColor: '#fff7ed',
    textColor: '#111827',
  },
  elementDefaults: {
    icon: true,
    icon2: true,
    date: true,
    title: true,
    text: false,
    author: true,
    count: true,
    qrcode: false,
    page: false,
    watermark: true,
  },
};
